### PR TITLE
Rename file and update plugin name

### LINKED ISSUE #1: Create basic WP plugin
Create a simple working plugin that does something.

E.g https://www.wpbeginner.com/wp-tutorials/how-to-create-a-wordpress-plugin/

### PR DESCRIPTION
**Pull request by odehgreg**
This Pull Request introduces the Ng Word Games plugin for WordPress. The main changes include renaming the plugin file to "naija_guru.php" and updating the plugin name  to "Ng Word Games." These changes enhance clarity and consistency within the project. The restructuring ensures that the plugin aligns with project standards and follows best practices. This PR is linked to Issue #1 for tracking purposes.

### CODE REVIEW

**Comment by nicholaskajoh** [comment]
Also use the imperative mood for PR titles i.e Rename file and update plugin name.

**Comment by nicholaskajoh** [comment]
Your commit messages should not start with a hyphen.

Here's another article on commit messages. You can ignore the conventional commit section if you want (no strong opinions there). https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

**Review by nicholaskajoh — APPROVED** [review]

**Comment by odehgreg** [comment]
> Also use the imperative mood for PR titles i.e Rename file and update plugin name.

okay noted , thank you boss

**Comment by odehgreg** [comment]
> Your commit messages should not start with a hyphen.
> 
> Here's another article on commit messages. You can ignore the conventional commit section if you want (no strong opinions there). https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

okay thank you very  much

**Pull request merged**
